# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150907194702 on 2015-09-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('str_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('organising_cost', models.IntegerField()),
                ('details', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('income', models.IntegerField()),
                ('members_count', models.IntegerField()),
                ('prob_list', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('receiving_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('net_bal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adoption_date', models.DateField()),
                ('family_count', models.IntegerField()),
                ('block', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('contact', models.IntegerField()),
                ('working_hrs', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_app.Village'),
        ),
        migrations.AddField(
            model_name='camp',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_app.Village'),
        ),
    ]
