# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150907194702 on 2015-10-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0003_auto_20151012_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='str_time',
            new_name='strt_time',
        ),
        migrations.AddField(
            model_name='camp',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='family',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='village',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
