# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150907194702 on 2015-10-15 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0004_auto_20151015_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='working_hrs',
            field=models.IntegerField(null=True),
        ),
    ]
