# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150907194702 on 2015-11-05 12:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='details',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='camp',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='organising_cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='strt_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='prob_list',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='village',
            name='adoption_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='family_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='joining_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='working_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='camp',
            unique_together=set([('camp_type', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together=set([('head_name', 'father_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='fund',
            unique_together=set([('source', 'receiving_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=set([('name', 'block')]),
        ),
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together=set([('name', 'contact')]),
        ),
    ]
