# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150907194702 on 2015-11-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0007_auto_20151105_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='net_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
    ]
