# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150907194702 on 2015-11-06 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0008_auto_20151106_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='working_hrs',
        ),
    ]
